default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  ingestion:
    <<: *default
    database: storage/development_ingestion.sqlite3
    migrations_paths: db/migrate_ingestion

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  ingestion:
    <<: *default
    database: storage/test_ingestion.sqlite3
    migrations_paths: db/migrate_ingestion

# TODO: make DB paths easily configurable based upon deploy
production:
  primary:
    <<: *default
    database: /mnt/volume_nyc1_gameguru/tiny_pixel/storage/db/production.sqlite3
  ingestion:
    <<: *default
    database: /mnt/volume_nyc1_gameguru/tiny_pixel/storage/db/production_ingestion.sqlite3
    migrations_paths: db/migrate_ingestion
