service: tiny_pixel
image: ghcr.io/mjc-gh/tiny_pixel
servers:
  web:
    hosts:
      - <%= ENV.fetch("KAMAL_WEB_HOST") %>
  workers:
    hosts:
      - <%= ENV.fetch("KAMAL_WEB_HOST") %>
    cmd: ./bin/jobs
registry:
  server: ghcr.io
  username: mjc-gh
  password:
    - KAMAL_REGISTRY_PASSWORD
volumes:
  - "<%= ENV.fetch("KAMAL_VOLUME_PATH") %>:/rails/storage"
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
proxy:
  hosts:
    - "<%= ENV.fetch("KAMAL_PROXY_HOST") %>"
  ssl: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
