periodic_jobs: &periodic_jobs
  hourly_aggregation:
    class: AggregationJob
    queue: aggregation
    args: []
    schedule: every hour

development:
  <<: *periodic_jobs

production:
  <<: *periodic_jobs
