default: &default
  allow_registration: <%= ENV.fetch("TP_ALLOW_REGISTRAION", "false") %>
  action_mailer_delivery: <%= ENV.fetch("TP_ACTION_MAILER_DELIVERY", "none") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
